FROM rasa/rasa-x:latest

WORKDIR /app

COPY channels/ ./channels

COPY data/ ./data

COPY models/ ./models

COPY config.yml . 

COPY credentials.yml .

COPY domain.yml .

COPY endpoints.yml .

USER root

RUN pip install -r channels/requirements-channels.txt

USER 1001

CMD ["x", "--credentials", "credentials.yml"]